spring:
  application:
    name: order-processor

server:
  port: 8082

spring.kafka:
  bootstrap-servers: localhost:9093

app:
  kafka:
    schema-registry-url: http://localhost:8085
    ssl:
      trust-store-location: ${KAFKA_CERTS_DIR:../kafka/certs}/client.truststore.jks
      key-store-location: ${KAFKA_CERTS_DIR:../kafka/certs}/client.keystore.jks
      store-password: changeit
    consumer:
      group-id: order-processor-group

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.demo.kafka: INFO
    org.apache.kafka: WARN
